# Generated by Django 5.0.4 on 2024-09-09 11:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_company_faqentry_news_partner_product_vacancy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Company',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=255)),
        #         ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
        #         ('video', models.FileField(blank=True, null=True, upload_to='company_videos/')),
        #         ('history', models.TextField(blank=True, null=True)),
        #         ('legal_name', models.CharField(max_length=255)),
        #         ('address', models.CharField(max_length=255)),
        #         ('registration_number', models.CharField(max_length=20)),
        #         ('bank_details', models.TextField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='FAQEntry',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('question', models.CharField(max_length=255)),
        #         ('answer', models.TextField()),
        #         ('date_added', models.DateField(auto_now_add=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='News',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=50)),
        #         ('image', models.ImageField(blank=True, null=True, upload_to='news_images')),
        #         ('content', models.TextField()),
        #         ('summary', models.TextField(default='')),
        #         ('time_create', models.DateTimeField(default=django.utils.timezone.now)),
        #         ('time_update', models.DateTimeField(auto_now=True)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Vacancy',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=100)),
        #         ('description', models.TextField()),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Review',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('rating', models.IntegerField()),
        #         ('text', models.TextField()),
        #         ('date', models.DateField(auto_now_add=True)),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
    ]
