# Generated by Django 5.0.4 on 2024-09-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_company_faqentry_news_partner_product_vacancy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
