# Generated by Django 5.0.4 on 2024-09-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_company_faqentry_news_vacancy_review'),
        ('mainapp', '0004_news_summary'),
    ]

    operations = [
    ]
