# Generated by Django 5.0.4 on 2024-09-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_merge_20240909_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sertificate',
            field=models.FileField(blank=True, null=True, upload_to='company_sertificate'),
        ),
    ]
