# Generated by Django 5.0.4 on 2024-10-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_company_sertificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vacancy_images'),
        ),
    ]
