# Generated by Django 5.0.4 on 2024-05-18 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images')),
                ('content', models.TextField()),
                ('time_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='about',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
