# Generated by Django 5.0.4 on 2024-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_discount_promocode_alter_ticket_weekday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='discount_percentage',
            field=models.PositiveIntegerField(),
        ),
    ]
