# Generated by Django 5.0.4 on 2024-05-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_customer_image_employee_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
