# Generated by Django 5.0.4 on 2024-05-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_customer_time_create_customer_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='spendings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
