# Generated by Django 5.0.4 on 2024-05-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_customer_spendings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='spendings',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
