# Generated by Django 5.0.4 on 2024-05-17 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_employee_first_name_remove_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customer',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
