# Generated by Django 5.0.4 on 2024-05-18 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_time_create_ticket_time_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='weekday',
            field=models.DateField(default=datetime.date(2024, 5, 18)),
        ),
    ]
