# Generated by Django 5.0.4 on 2024-09-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_alter_ticket_weekday_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='time_update',
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
