# Generated by Django 5.0.4 on 2024-09-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_remove_cart_time_create_remove_cart_time_update_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
