# Generated by Django 5.0.4 on 2024-09-09 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='weekday',
            field=models.DateField(default=datetime.date(2024, 9, 9)),
        ),
    ]
