# Generated by Django 5.0.4 on 2024-10-05 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_ticket_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='weekday',
            field=models.DateField(default=datetime.date(2024, 10, 5)),
        ),
    ]
