# Generated by Django 5.0.4 on 2024-05-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_options_alter_country_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='countries',
            new_name='country',
        ),
    ]
