# Generated by Django 5.0.4 on 2024-05-02 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animalclass_animal_animal_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='animal_class',
        ),
    ]
