# Generated by Django 5.0.4 on 2024-05-02 15:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_animal_animal_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='time_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='animal',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
