# Generated by Django 5.0.4 on 2024-05-02 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_remove_animal_animal_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='animals.animalclass'),
        ),
    ]
